var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/(app)/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0q55lp5._.js")
R.c("server/chunks/ssr/node_modules_0ev7kv1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0tri-c4.js")
R.c("server/chunks/ssr/[root-of-the-server]__09d208w._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ob90to._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1jc2iif._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_0aby7t2._.js")
R.c("server/chunks/ssr/_195su8x._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(app)_page_actions_1gxdy57.js")
R.m(34699)
module.exports=R.m(34699).exports
