var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(app)/session/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__03k0hl6._.js")
R.c("server/chunks/ssr/node_modules_0ev7kv1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_00hwh1c.js")
R.c("server/chunks/ssr/[root-of-the-server]__09d208w._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ob90to._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1jc2iif._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_0aby7t2._.js")
R.c("server/chunks/ssr/_195su8x._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(app)_session_[id]_page_actions_1boej34.js")
R.m(46194)
module.exports=R.m(46194).exports
